<?php

namespace AppBundle\Repository;

/**
 * CertificateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CertificateRepository extends \Doctrine\ORM\EntityRepository
{
}
