<?php

namespace AppBundle\Repository;

/**
 * SommeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SommeRepository extends \Doctrine\ORM\EntityRepository
{
}
